const products = [
  {
    pid: "product1",
    name: "Nike Air Max 90",
    description: "A versatile running shoe offering support and comfort.",
    img: "images\\1.jpeg",
    price: 12000,
    offerPrice: 10500,
    gender: "men",
    color: "white",
    brand: "nike",
    category: "casual",
    material: "leather",
    rating: 4.5,
    type: "sneaker"
  },
  {
    pid: "product2",
    name: "Adidas Ultraboost",
    description: "A high-performance running shoe designed for ultimate comfort.",
    img: "images\\2.jpeg",
    price: 15000,
    offerPrice: 13500,
    gender: "men",
    color: "black",
    brand: "adidas",
    category: "sport",
    material: "mesh",
    rating: 4.8,
    type: "running shoe"
  },
  {
    pid: "product3",
    name: "Puma Ignite",
    description: "A stylish athletic shoe for high-intensity workouts.",
    img: "images\\3.jpeg",
    price: 8500,
    offerPrice: 7500,
    gender: "men",
    color: "red",
    brand: "puma",
    category: "sport",
    material: "synthetic",
    rating: 4.3,
    type: "athletic shoe"
  },
  {
    pid: "product4",
    name: "Reebok Classic Leather",
    description: "Classic leather sneakers with a retro feel, perfect for everyday wear.",
    img: "images\\4.jpeg",
    price: 9999,
    offerPrice: 8999,
    gender: "men",
    color: "grey",
    brand: "reebok",
    category: "casual",
    material: "leather",
    rating: 4.2,
    type: "sneaker"
  },
  {
    pid: "product5",
    name: "Adidas Stan Smith",
    description: "A timeless classic sneaker, perfect for casual looks.",
    img: "images\\5.jpeg",
    price: 8500,
    offerPrice: 7600,
    gender: "men",
    color: "white",
    brand: "adidas",
    category: "casual",
    material: "leather",
    rating: 4.6,
    type: "sneaker"
  },
  {
    pid: "product6",
    name: "Nike Free RN",
    description: "Lightweight running shoes designed for natural movement.",
    img: "images\\6.jpeg",
    price: 14000,
    offerPrice: 12000,
    gender: "men",
    color: "blue",
    brand: "nike",
    category: "sport",
    material: "mesh",
    rating: 4.7,
    type: "running shoe"
  },
  {
    pid: "product7",
    name: "Nike Air Force 1",
    description: "Iconic sneakers known for comfort and style.",
    img: "images\\7.jpeg",
    price: 10500,
    offerPrice: 9500,
    gender: "men",
    color: "black",
    brand: "nike",
    category: "casual",
    material: "leather",
    rating: 4.4,
    type: "sneaker"
  },
  {
    pid: "product8",
    name: "Puma RS-X3",
    description: "A modern, streetwear-inspired sneaker.",
    img: "images\\8.jpeg",
    price: 9500,
    offerPrice: 8500,
    gender: "men",
    color: "green",
    brand: "puma",
    category: "casual",
    material: "synthetic",
    rating: 4.0,
    type: "sneaker"
  },
  {
    pid: "product9",
    name: "Adidas NMD R1",
    description: "Stylish and comfortable, a perfect urban sneaker.",
    img: "images\\9.jpeg",
    price: 13500,
    offerPrice: 12500,
    gender: "men",
    color: "black",
    brand: "adidas",
    category: "casual",
    material: "knit",
    rating: 4.5,
    type: "sneaker"
  },
  {
    pid: "product10",
    name: "Nike Zoom Pegasus 37",
    description: "Running shoes designed for maximum speed and comfort.",
    img: "images\\10.jpeg",
    price: 13000,
    offerPrice: 11500,
    gender: "men",
    color: "red",
    brand: "nike",
    category: "sport",
    material: "mesh",
    rating: 4.6,
    type: "running shoe"
  },
  {
    pid: "product11",
    name: "Nike Air Max 270",
    description: "Combines sporty and casual designs, offering a stylish look.",
    img: "images\\11.jpeg",
    price: 15000,
    offerPrice: 13500,
    gender: "women",
    color: "pink",
    brand: "nike",
    category: "casual",
    material: "mesh",
    rating: 4.8,
    type: "sneaker"
  },
  {
    pid: "product12",
    name: "Adidas UltraBoost 21",
    description: "The ultimate in comfort and performance for women’s feet.",
    img: "images\\12.jpeg",
    price: 18000,
    offerPrice: 16000,
    gender: "women",
    color: "white",
    brand: "adidas",
    category: "sport",
    material: "knit",
    rating: 4.7,
    type: "running shoe"
  },
  {
    pid: "product13",
    name: "Puma Suede Classic",
    description: "A casual sneaker made of suede, offering style and comfort.",
    img: "images\\13.jpeg",
    price: 9000,
    offerPrice: 7500,
    gender: "women",
    color: "red",
    brand: "puma",
    category: "casual",
    material: "suede",
    rating: 4.2,
    type: "sneaker"
  },
  {
    pid: "product14",
    name: "Reebok Freestyle Hi",
    description: "Retro high-top sneakers that offer both style and comfort.",
    img: "images\\14.jpeg",
    price: 12000,
    offerPrice: 10500,
    gender: "women",
    color: "blue",
    brand: "reebok",
    category: "casual",
    material: "leather",
    rating: 4.4,
    type: "sneaker"
  },
  {
    pid: "product15",
    name: "Adidas Gazelle",
    description: "A retro-inspired sneaker for women with timeless appeal.",
    img: "images\\15.jpeg",
    price: 9500,
    offerPrice: 8500,
    gender: "women",
    color: "green",
    brand: "adidas",
    category: "casual",
    material: "suede",
    rating: 4.6,
    type: "sneaker"
  },
  {
    pid: "product16",
    name: "Nike Air Max 97",
    description: "A stylish and comfortable sneaker designed for everyday use.",
    img: "images\\16.jpeg",
    price: 14000,
    offerPrice: 12000,
    gender: "women",
    color: "white",
    brand: "nike",
    category: "casual",
    material: "leather",
    rating: 4.5,
    type: "sneaker"
  },
  {
    pid: "product17",
    name: "Adidas Superstar",
    description: "The iconic shell-toe sneaker with a timeless design.",
    img: "images\\17.jpeg",
    price: 11000,
    offerPrice: 9500,
    gender: "women",
    color: "pink",
    brand: "adidas",
    category: "casual",
    material: "leather",
    rating: 4.7,
    type: "sneaker"
  },
  {
    pid: "product18",
    name: "Nike Tanjun",
    description: "Minimalistic and comfortable sneakers for everyday wear.",
    img: "images\\18.jpeg",
    price: 8500,
    offerPrice: 7500,
    gender: "women",
    color: "black",
    brand: "nike",
    category: "casual",
    material: "mesh",
    rating: 4.3,
    type: "sneaker"
  },
  {
    pid: "product19",
    name: "Puma Future Rider",
    description: "A modern shoe with a retro twist, great for casual outfits.",
    img: "images\\19.jpeg",
    price: 10000,
    offerPrice: 9000,
    gender: "women",
    color: "yellow",
    brand: "puma",
    category: "casual",
    material: "synthetic",
    rating: 4.2,
    type: "sneaker"
  },
  {
    pid: "product20",
    name: "Adidas Swift Run",
    description: "Sporty and comfortable running shoes for women.",
    img: "images\\20.jpeg",
    price: 9500,
    offerPrice: 8500,
    gender: "women",
    color: "grey",
    brand: "adidas",
    category: "sport",
    material: "mesh",
    rating: 4.6,
    type: "running shoe"
  },
  {
    pid: "product21",
    name: "Nike Tanjun",
    description: "Comfortable everyday sneakers for casual wear.",
    img: "images\\21.jpeg",
    price: 6000,
    offerPrice: 5500,
    gender: "kid",
    color: "pink",
    brand: "nike",
    category: "casual",
    material: "mesh",
    rating: 4.2,
    type: "sneaker"
  },
  {
    pid: "product22",
    name: "Adidas Stan Smith Kids",
    description: "A smaller version of the iconic Stan Smith sneaker.",
    img: "images\\22.jpeg",
    price: 5000,
    offerPrice: 4500,
    gender: "kid",
    color: "white",
    brand: "adidas",
    category: "casual",
    material: "leather",
    rating: 4.3,
    type: "sneaker"
  },
  {
    pid: "product23",
    name: "Puma Future Rider Kids",
    description: "A colorful and fun sneaker for kids with a retro vibe.",
    img: "images\\23.jpeg",
    price: 5500,
    offerPrice: 5000,
    gender: "kid",
    color: "red",
    brand: "puma",
    category: "casual",
    material: "synthetic",
    rating: 4.4,
    type: "sneaker"
  },
  {
    pid: "product24",
    name: "Nike Air Max 270 Kids",
    description: "Comfortable and stylish sneakers designed for kids.",
    img: "images\\24.jpeg",
    price: 6500,
    offerPrice: 6000,
    gender: "kid",
    color: "blue",
    brand: "nike",
    category: "casual",
    material: "mesh",
    rating: 4.5,
    type: "sneaker"
  },
  {
    pid: "product25",
    name: "Adidas NMD R1 Kids",
    description: "A sleek, comfortable sneaker with a stylish design.",
    img: "images\\25.jpeg",
    price: 7000,
    offerPrice: 6500,
    gender: "kid",
    color: "black",
    brand: "adidas",
    category: "casual",
    material: "knit",
    rating: 4.6,
    type: "sneaker"
  },
  { 
    pid: "product26",
    name: "Skechers Women's Sandals",
    description: "Comfortable sandals with arch support for casual walks",
    img: "images\\26.jpeg",
    price: 4500,
    offerPrice: 4000,
    gender: "women",
    color: "beige",
    brand: "skechers",
    category: "casual",
    material: "synthetic",
    rating: 4.5,
    type: "sandal"
  },
  {
    pid: "product27",
    name: "Crocs Women's Flip Flops",
    description: "Lightweight flip-flops ideal for beachwear",
    img: "images\\27.jpeg",
    price: 2500,
    offerPrice: 2200,
    gender: "women",
    color: "navy blue",
    brand: "crocs",
    category: "casual",
    material: "rubber",
    rating: 4.2,
    type: "flip flop"
  },
  {
    pid: "product28",
    name: "Aerosoles Women's Heeled Sandals",
    description: "Stylish heels that combine comfort with chic looks",
    img: "images\\28.jpeg",
    price: 8000,
    offerPrice: 7200,
    gender: "women",
    color: "black",
    brand: "aerosoles",
    category: "formal",
    material: "leather",
    rating: 4.0,
    type: "heel"
  },
  {
    pid: "product29",
    name: "Clarks Women's Dress Heels",
    description: "Elegant dress heels for formal occasions",
    img: "images\\29.jpeg",
    price: 9500,
    offerPrice: 9000,
    gender: "women",
    color: "red",
    brand: "clarks",
    category: "formal",
    material: "leather",
    rating: 4.6,
    type: "heel"
  },
  {
    pid: "product30",
    name: "Hush Puppies Women's Sandals",
    description: "Soft and comfortable sandals perfect for summer",
    img: "images\\30.jpeg",
    price: 7000,
    offerPrice: 6500,
    gender: "women",
    color: "brown",
    brand: "hush puppies",
    category: "casual",
    material: "leather",
    rating: 4.3,
    type: "sandal"
  },
  {
    pid: "product31",
    name: "Timberland Men's Formal Shoes",
    description: "Timeless leather formal shoes for professional settings",
    img: "images\\31.jpeg",
    price: 12000,
    offerPrice: 11000,
    gender: "men",
    color: "black",
    brand: "timberland",
    category: "formal",
    material: "leather",
    rating: 4.5,
    type: "shoe"
  },
  {
    pid: "product32",
    name: "Nike Air Max 90 Sandals",
    description: "Comfortable, sporty sandals with cushioning",
    img: "images\\32.jpeg",
    price: 7000,
    offerPrice: 6200,
    gender: "men",
    color: "grey",
    brand: "nike",
    category: "casual",
    material: "synthetic",
    rating: 4.2,
    type: "sandal"
  },
  {
    pid: "product33",
    name: "Adidas Men's Flip Flops",
    description: "Durable and comfortable flip-flops perfect for the beach",
    img: "images\\33.jpeg",
    price: 2500,
    offerPrice: 2300,
    gender: "men",
    color: "black",
    brand: "adidas",
    category: "casual",
    material: "rubber",
    rating: 4.3,
    type: "flip flop"
  },
  {
    pid: "product34",
    name: "Bata Men's Formal Leather Shoes",
    description: "Classic leather shoes for formal occasions and office wear",
    img: "images\\34.jpeg",
    price: 8500,
    offerPrice: 7700,
    gender: "men",
    color: "brown",
    brand: "bata",
    category: "formal",
    material: "leather",
    rating: 4.0,
    type: "shoe"
  },
  {
    pid: "product35",
    name: "Allen Edmonds Men's Oxford Shoes",
    description: "High-quality, durable oxford shoes perfect for business meetings",
    img: "images\\35.jpeg",
    price: 25000,
    offerPrice: 23000,
    gender: "men",
    color: "black",
    brand: "allen edmonds",
    category: "formal",
    material: "leather",
    rating: 5.0,
    type: "shoe"
  },
  {
    pid: "product36",
    name: "Dr. Martens Men's Chelsea Boots",
    description: "Iconic boots offering both style and comfort",
    img: "images\\36.jpeg",
    price: 18000,
    offerPrice: 16000,
    gender: "men",
    color: "black",
    brand: "dr. martens",
    category: "casual",
    material: "leather",
    rating: 4.4,
    type: "boot"
  },
  {
    pid: "product37",
    name: "UGG Women's Heeled Boots",
    description: "Warm, stylish heeled boots perfect for winter days",
    img: "images\\37.jpeg",
    price: 13000,
    offerPrice: 12000,
    gender: "women",
    color: "brown",
    brand: "ugg",
    category: "casual",
    material: "suede",
    rating: 4.5,
    type: "boot"
  },
  { 
    pid: "product38",
    name: "Teva Women's Sandals",
    description: "Sporty sandals designed for outdoor adventures.",
    img: "images\\38.jpeg",
    price: 6500,
    offerPrice: 6000,
    gender: "women",
    color: "blue",
    brand: "teva",
    category: "casual",
    material: "synthetic",
    rating: 4.6,
    type: "sandal"
  },
  {
    pid: "product39",
    name: "Sperry Top-Sider Men's Boat Shoes",
    description: "Classic boat shoes, perfect for nautical and casual looks.",
    img: "images\\39.jpeg",
    price: 11000,
    offerPrice: 9500,
    gender: "men",
    color: "brown",
    brand: "sperry top-sider",
    category: "casual",
    material: "leather",
    rating: 4.4,
    type: "shoe"
  },
  {
    pid: "product40",
    name: "Cole Haan Men's Dress Shoes",
    description: "Elegant leather dress shoes, ideal for formal settings.",
    img: "images\\40.jpeg",
    price: 15000,
    offerPrice: 14000,
    gender: "men",
    color: "black",
    brand: "cole haan",
    category: "formal",
    material: "leather",
    rating: 4.8,
    type: "shoe"
  },
  {
    pid: "product41",
    name: "Sam Edelman Women's Pumps",
    description: "Chic and stylish high heels for a fashionable look.",
    img: "images\\41.jpeg",
    price: 12000,
    offerPrice: 10000,
    gender: "women",
    color: "nude",
    brand: "sam edelman",
    category: "formal",
    material: "leather",
    rating: 4.2,
    type: "heel"
  },
  {
    pid: "product42",
    name: "Vans Men's Slip-On Sneakers",
    description: "Comfortable slip-on shoes with a classic design.",
    img: "images\\42.jpeg",
    price: 4500,
    offerPrice: 4000,
    gender: "men",
    color: "white",
    brand: "vans",
    category: "casual",
    material: "canvas",
    rating: 4.3,
    type: "sneaker"
  },
  {
    pid: "product43",
    name: "Birkenstock Women's Sandals",
    description: "Comfortable sandals designed for all-day wear.",
    img: "images\\43.jpeg",
    price: 8500,
    offerPrice: 7500,
    gender: "women",
    color: "brown",
    brand: "birkenstock",
    category: "casual",
    material: "leather",
    rating: 4.4,
    type: "sandal"
  },
  {
    pid: "product44",
    name: "Rockport Men's Dress Shoes",
    description: "Leather dress shoes combining comfort and professional style.",
    img: "images\\44.jpeg",
    price: 11000,
    offerPrice: 10000,
    gender: "men",
    color: "brown",
    brand: "rockport",
    category: "formal",
    material: "leather",
    rating: 4.7,
    type: "shoe"
  },
  {
    pid: "product45",
    name: "Tommy Hilfiger Women's Sandals",
    description: "Stylish and fashionable sandals for beachwear and casual outings.",
    img: "images\\45.jpeg",
    price: 6000,
    offerPrice: 5500,
    gender: "women",
    color: "navy blue",
    brand: "tommy hilfiger",
    category: "casual",
    material: "synthetic",
    rating: 4.0,
    type: "sandal"
  },
  {
    pid: "product46",
    name: "Nike Kid's Air Max Sneakers",
    description: "Sporty and comfortable sneakers designed for active kids.",
    img: "images\\46.jpeg",
    price: 5000,
    offerPrice: 4500,
    gender: "kid",
    color: "blue",
    brand: "nike",
    category: "casual",
    material: "synthetic",
    rating: 4.7,
    type: "sneaker"
  },
  {
    pid: "product47",
    name: "Adidas Kid's Running Shoes",
    description: "Durable running shoes that provide support for little athletes.",
    img: "images\\47.jpeg",
    price: 4200,
    offerPrice: 3800,
    gender: "kid",
    color: "red",
    brand: "adidas",
    category: "casual",
    material: "mesh",
    rating: 4.6,
    type: "shoe"
  },
  {
    pid: "product48",
    name: "Crocs Kid's Flip Flops",
    description: "Fun and comfortable flip-flops for outdoor play.",
    img: "images\\48.jpeg",
    price: 2000,
    offerPrice: 1800,
    gender: "kid",
    color: "pink",
    brand: "crocs",
    category: "casual",
    material: "rubber",
    rating: 4.4,
    type: "flip flop"
  },
  {
    pid: "product49",
    name: "Skechers Kid's Light-Up Sneakers",
    description: "Fun light-up sneakers that kids will love wearing.",
    img: "images\\49.jpeg",
    price: 4500,
    offerPrice: 4000,
    gender: "kid",
    color: "black",
    brand: "skechers",
    category: "casual",
    material: "synthetic",
    rating: 4.8,
    type: "sneaker"
  },
  {
    pid: "product50",
    name: "Puma Kid's Sporty Sandals",
    description: "Breathable sandals perfect for outdoor adventures and water play.",
    img: "images\\50.jpeg",
    price: 3200,
    offerPrice: 2800,
    gender: "kid",
    color: "yellow",
    brand: "puma",
    category: "casual",
    material: "synthetic",
    rating: 4.5,
    type: "sandal"
  }
];

localStorage.setItem('products', JSON.stringify(products));
